#!/usr/bin/env bash
# scripts/diagnose-hosting-auth.sh
#
# Probe a real WordPress host to confirm Application Password authentication
# works end-to-end through whatever proxy / WAF / mod_security / Cloudflare /
# security plugin is in front of WordPress.
#
# This is the script to run when:
#   - "It works locally but 401s on production" — proves whether the host is
#     stripping Authorization headers.
#   - You want a one-shot pass/fail before handing a connection pack to an AI.
#   - You're debugging Cloudflare / WAF / iThemes Security / Wordfence
#     interference.
#
# Usage:
#   scripts/diagnose-hosting-auth.sh https://example.com ai-agent 'xxxx xxxx xxxx xxxx xxxx xxxx'
#
# Or via env vars (preferred — keeps the password out of shell history):
#   export ASC_SITE='https://example.com'
#   export ASC_USER='ai-agent'
#   read -rs -p 'app password: ' ASC_PWD; export ASC_PWD
#   scripts/diagnose-hosting-auth.sh
#
# The Application Password is never echoed in full — only the last 4 chars
# appear in output, and curl is invoked with --user (no shell-visible quoting
# of the secret on the command line beyond this process).

set -euo pipefail

SITE="${1:-${ASC_SITE:-}}"
USER="${2:-${ASC_USER:-}}"
PWD_IN="${3:-${ASC_PWD:-}}"

red()    { printf '\033[31m%s\033[0m\n' "$*"; }
green()  { printf '\033[32m%s\033[0m\n' "$*"; }
yellow() { printf '\033[33m%s\033[0m\n' "$*"; }
hr()     { printf '\n\033[1;36m── %s\033[0m\n' "$*"; }
pass()   { green "  PASS: $*"; }
warn()   { yellow "  WARN: $*"; }
fail()   { red "  FAIL: $*"; FAILS=$((FAILS+1)); }
hint()   { printf '         \033[2m↳ %s\033[0m\n' "$*"; }

usage() {
	cat <<USAGE
Usage:
  $0 <site_url> <username> <application_password>

  Or set ASC_SITE / ASC_USER / ASC_PWD environment variables.

  Site URL examples:
    https://example.com
    https://wp.example.com/blog

  The Application Password is the 24-character credential generated by:
    wp ai-connector generate-password --username=ai-agent
  or via Tools → AI Site Connector → Credentials in wp-admin.
USAGE
}

if [ -z "$SITE" ] || [ -z "$USER" ] || [ -z "$PWD_IN" ]; then
	usage; exit 2
fi

command -v curl >/dev/null 2>&1 || { red "curl is required"; exit 2; }
command -v jq   >/dev/null 2>&1 || { red "jq is required"; exit 2; }

# Trim trailing slash for consistency.
SITE="${SITE%/}"
PWD_TAIL="…${PWD_IN: -4}"
FAILS=0

hr "target"
echo "  site:     $SITE"
echo "  user:     $USER"
echo "  password: ${PWD_TAIL}  (only the last 4 characters are ever printed)"

# Reusable curl wrappers ------------------------------------------------------
_curl_code() {
	# args: url [extra-curl-args...]
	# Returns HTTP code on stdout; never prints body.
	local url="$1"; shift
	curl -sS -o /dev/null -w '%{http_code}' --max-time 15 "$@" "$url" || echo "000"
}
_curl_body() {
	local url="$1"; shift
	curl -sS --max-time 15 "$@" "$url" || true
}
_auth=( --user "${USER}:${PWD_IN}" )

# --------------------------------------------------------------------- 1. HTTPS
hr "1. HTTPS"
case "$SITE" in
	https://*) pass "site URL uses https" ;;
	http://*)
		fail "site URL is plain HTTP"
		hint "WordPress refuses to mint Application Passwords over HTTP unless WP_DEBUG"
		hint "or AI_SITE_CONNECTOR_ALLOW_HTTP is defined. Configure SSL on the host."
		;;
	*)  fail "site URL has no scheme" ;;
esac

# --------------------------------------------------------------------- 2. REST root
hr "2. REST root reachable"
ROOT_CODE="$(_curl_code "${SITE}/wp-json/")"
if [ "$ROOT_CODE" = "200" ]; then
	pass "/wp-json/ returned 200"
elif [ "$ROOT_CODE" = "404" ]; then
	fail "/wp-json/ returned 404"
	hint "REST API may be disabled by a security plugin or .htaccess rule."
	hint "Try the index.php fallback: ${SITE}/?rest_route=/"
	ALT="$(_curl_code "${SITE}/?rest_route=/")"
	if [ "$ALT" = "200" ]; then
		warn "the index.php REST fallback works (${ALT}) — pretty permalinks are not active"
		hint "Settings → Permalinks → set anything other than Plain, then save."
	fi
elif [ "$ROOT_CODE" = "000" ]; then
	fail "could not reach $SITE at all (timeout / DNS / blocked)"
	hint "Try: curl -v ${SITE}/wp-json/  to see TLS / DNS / connection errors."
else
	fail "/wp-json/ returned $ROOT_CODE"
fi

# --------------------------------------------------------------------- 3. plugin /health unauth
hr "3. AI Site Connector /health (unauth)"
HEALTH_BODY="$(_curl_body "${SITE}/wp-json/ai-site-connector/v1/health")"
if [ -n "$HEALTH_BODY" ] && echo "$HEALTH_BODY" | jq -e '.plugin == "ai-site-connector"' >/dev/null 2>&1; then
	pass "plugin is installed and the public health endpoint responds"
	# Confirm minimal payload — we should NOT see wp_version / php_version etc.
	if echo "$HEALTH_BODY" | jq -e 'has("wp_version") or has("php_version") or has("active_theme") or has("user")' >/dev/null 2>&1; then
		fail "/health unauth is leaking sensitive fields (wp_version, php_version, active_theme, user)"
		hint "This means the plugin on the host is older than the hardened version."
		hint "Update to the latest release."
	else
		pass "/health unauth payload is minimal (no wp_version / php_version / theme / user leak)"
	fi
	HTTPS_OK="$(echo "$HEALTH_BODY" | jq -r '.https')"
	if [ "$HTTPS_OK" = "true" ]; then
		pass "the plugin reports https=true (TLS terminated where WordPress sees it)"
	else
		warn "the plugin reports https=false even though we're talking over HTTPS"
		hint "A reverse proxy is likely terminating TLS without setting X-Forwarded-Proto."
		hint "Add the proxy header or set FORCE_SSL_ADMIN in wp-config.php."
	fi
else
	fail "no recognizable response from /wp-json/ai-site-connector/v1/health"
	hint "Either the plugin isn't installed/active, or a WAF is intercepting the path."
fi

# --------------------------------------------------------------------- 4. authenticated wp/v2/users/me
hr "4. wp/v2/users/me with Application Password (the canonical auth test)"
ME_BODY="$(_curl_body "${SITE}/wp-json/wp/v2/users/me" "${_auth[@]}")"
ME_CODE="$(_curl_code "${SITE}/wp-json/wp/v2/users/me" "${_auth[@]}")"

case "$ME_CODE" in
	200)
		pass "Application Password authenticated — HTTP 200"
		who="$(echo "$ME_BODY" | jq -r '.slug // .name // empty')"
		[ -n "$who" ] && pass "authenticated as: $who"
		;;
	401)
		fail "401 Unauthorized — credentials rejected"
		hint "Most likely cause #1: hosting strips the Authorization header. Add to .htaccess:"
		hint "  RewriteEngine On"
		hint "  RewriteCond %{HTTP:Authorization} ^(.*)"
		hint "  RewriteRule .* - [E=HTTP_AUTHORIZATION:%1]"
		hint "Most likely cause #2: the App Password was revoked or the user was deleted."
		hint "Most likely cause #3: a security plugin (Wordfence, iThemes Security, WP Cerber) is blocking REST or Basic Auth."
		;;
	403)
		warn "403 Forbidden — auth was accepted but capability denied"
		hint "Confirm the user role has the capabilities required for the endpoint."
		;;
	404)
		fail "404 Not Found"
		hint "REST may be disabled, or pretty permalinks aren't flushed."
		;;
	429)
		warn "429 Too Many Requests — host or CF rate limit"
		;;
	5*)
		fail "${ME_CODE} server error"
		hint "Check site error logs. WordPress may have a fatal error in admin context."
		;;
	000)
		fail "connection failed"
		hint "TLS handshake or DNS resolution failed."
		;;
	*) fail "unexpected status: $ME_CODE" ;;
esac

# --------------------------------------------------------------------- 5. authenticated /health
hr "5. AI Site Connector /health (auth)"
HEALTH_AUTH="$(_curl_body "${SITE}/wp-json/ai-site-connector/v1/health" "${_auth[@]}")"
HEALTH_AUTH_CODE="$(_curl_code "${SITE}/wp-json/ai-site-connector/v1/health" "${_auth[@]}")"
if [ "$HEALTH_AUTH_CODE" = "200" ] && echo "$HEALTH_AUTH" | jq -e '.authenticated == true' >/dev/null 2>&1; then
	pass "authenticated /health returns rich payload"
	wp_v="$(echo "$HEALTH_AUTH" | jq -r '.wp_version // empty')"
	php_v="$(echo "$HEALTH_AUTH" | jq -r '.php_version // empty')"
	[ -n "$wp_v" ]  && echo "  WP version:  $wp_v"
	[ -n "$php_v" ] && echo "  PHP version: $php_v"
	role="$(echo "$HEALTH_AUTH" | jq -r '.user.roles | join(",")')"
	[ -n "$role" ] && echo "  user roles:  $role"
	if echo "$HEALTH_AUTH" | jq -e '.user.roles | index("administrator")' >/dev/null 2>&1; then
		warn "authenticated as an administrator — consider switching to ai_site_operator (least privilege)"
	fi
else
	fail "authenticated /health did not return rich payload (HTTP ${HEALTH_AUTH_CODE})"
fi

# --------------------------------------------------------------------- 6. WAF / mod_security probe
hr "6. WAF / mod_security probe (sends a benign POST that some WAFs panic on)"
WAF_CODE="$(curl -sS -o /dev/null -w '%{http_code}' --max-time 15 -X POST \
	-H 'Content-Type: application/json' \
	-d '{"smoke":"benign"}' \
	"${_auth[@]}" \
	"${SITE}/wp-json/wp/v2/users/me" || echo "000")"
case "$WAF_CODE" in
	405) pass "POST returned 405 (Method Not Allowed) — WordPress is making the call, not a WAF" ;;
	401) warn "POST returned 401 — Authorization header may be dropped only on writes" ;;
	403) warn "POST returned 403 — likely a WAF/mod_security false positive on JSON body" ;;
	200|201|202) warn "POST unexpectedly succeeded ($WAF_CODE)" ;;
	*) warn "POST returned $WAF_CODE — investigate" ;;
esac

# --------------------------------------------------------------------- 7. summary
hr "summary"
if [ "$FAILS" -eq 0 ]; then
	green "all checks passed — Application Password authentication works end-to-end against $SITE"
	exit 0
else
	red "${FAILS} check(s) failed — see hints above"
	exit 1
fi
